version: 2
models:
  - name: t_dim_fi_org
    description: Model for t_dim_fi_org
    columns:
      - name: fi_org_sk
        tests:
          - not_null
      - name: controlling_area
      - name: company_code_nk
      - name: company_nm
      - name: cost_center_nk
      - name: profit_center_nk
      - name: entity
      - name: cluster_code_nk
      - name: country_code_nk
      - name: country_nm
      - name: source_system

  - name: t_dim_account_cust_pnl
    description: Model for t_dim_account_cust_pnl
    columns:
      - name: account_cust_pnl_sk
        tests:
          - not_null
      - name: gl_account_nb_nk
      - name: company_code_nk
      - name: chart_of_accounts_directory_nk
      - name: pnl_statement_account_type
      - name: gl_account_type
      - name: group_account_number
      - name: source_system

  - name: t_dim_pnl_kpi
    description: Model for t_dim_pnl_kpi
    columns:
      - name: pnl_kpi_sk
        tests:
          - not_null
      - name: kpi_level_1
      - name: kpi_level_2
      - name: kpi_level_3
      - name: kpi_level_4
      - name: kpi_level_5
      - name: kpi_level_6
      - name: kpi_level_7
      - name: kpi_level_8
      - name: kpi_name
      - name: gl_account_nb_nk
      - name: cluster_code_nk
      - name: sign_multiplier
      - name: additive_flg
      - name: kpi_formula
      - name: source_system

  - name: t_fct_ma_customer_pnl
    description: Model for t_fct_ma_customer_pnl
    columns:
      - name: cal_sk
        tests:
          - not_null
      - name: account_cust_pnl_sk
        tests:
          - not_null
      - name: fi_org_sk
        tests:
          - not_null
      - name: customer_sk
        tests:
          - not_null
      - name: product_sk
        tests:
          - not_null
      - name: vendor_sk
        tests:
          - not_null
      - name: product_sold_sk
        tests:
          - not_null
      - name: pnl_kpi_sk
        tests:
          - not_null
      - name: units_sk
        tests:
          - not_null
      - name: plant_sk
        tests:
          - not_null
      - name: customer_salesarea_sk
        tests:
          - not_null
      - name: kpi_value_base_uom
      - name: kpi_value_cse
      - name: kpi_value_lbs
      - name: kpi_value_kgs
      - name: glbl_curr_kpi_value
      - name: lcl_curr_kpi_value
      - name: txn_curr_kpi_value

  - name: t_dim_product_cust_pnl
    description: Model for t_dim_product_cust_pnl
    columns:
      - name: product_sk
        tests:
          - not_null
      - name: product_cd_nk
      - name: product_type
      - name: is_current
      - name: validity_start_dt
      - name: validity_end_dt
      - name: product_type_cd
      - name: product_hierarchy_cd
      - name: product_group_cd
      - name: glbl_brand_cd
      - name: glbl_brand_nm
      - name: glbl_subbrand_nm
      - name: glbl_variant_nm
      - name: local_brand_cd
      - name: local_brand_ds
      - name: local_subbrand_cd
      - name: local_subbrand_ds
      - name: base_unit_of_measure_cd
      - name: net_contents_qt
      - name: content_unit_cd
      - name: net_weight_vl
      - name: weight_unit_cd
      - name: volume_vl
      - name: volume_unit_cd
      - name: glbl_gtin_nb
      - name: country_origin_cd
      - name: cross_plant_material_status_cd
      - name: deletion_client_level_fl
      - name: pricing_ref_material_cd
      - name: general_item_category_group_cd
      - name: snack_type
      - name: source_system
