version: 2
sources:
  - name: amer_h_saps4_am
    database: RAW
    schema: public
    tables:
      - name: t_acdoca
      - name: t_ska1
  - name: amer_h_manual_mst
    database: RAW
    schema: public
    tables:
      - name: t_nala_cstmr_pnl_kpi_mapping
  - name: amer_dc_md
    database: RAW
    schema: public
    tables:
      - name: t_dim_material
      - name: t_dim_company_code
      - name: t_dim_country