version: 2
sources:
  - name: meu_ds_lops
    database: RAW
    schema: public
    tables:
      - name: v_fct_shipment_order
        description: Driving table for BASE_INET_LOADS_DATASET
      - name: v_fct_shipment_load
        description: Shipment load details
      - name: v_fct_shipment_cost
        description: Shipment cost details
      - name: v_fct_shipment_orderdetail
        description: Shipment order detail
      - name: v_dim_vehicle
        description: Vehicle dimension table
      - name: v_dim_pick_up_delivery
        description: Pickup and delivery dimension
      - name: v_dim_transportation_coordinator
        description: Transportation coordinator (used as consignor/receiver)
