with source as (
  select * from {{ source('meu_ds_lops', 'v_fct_shipment_order') }}
)
select
  cast(internal_order_id_nk as string) as internal_order_id_nk,
  cast(internal_load_id_nk as string) as internal_load_id_nk,
  cast(costid_nk as string) as costid_nk,
  cast(internal_orderdetail_id_nk as string) as internal_orderdetail_id_nk,
  cast(to_bonus_time as string) as to_bonus_time,
  cast(to_order_number as string) as to_order_number,
  cast(to_load_number as string) as to_load_number,
  cast(ld_load_name as string) as ld_load_name,
  cast(means_of_transport as string) as means_of_transport,
  cast(to_special_order_type as string) as to_special_order_type,
  cast(to_act_pickup_date as string) as to_act_pickup_date,
  cast(co_total_costs as string) as co_total_costs,
  cast(co_cost_type as string) as co_cost_type,
  cast(to_weight_unit as string) as to_weight_unit,
  cast(to_gross_weight as string) as to_gross_weight,
  cast(packagetype as string) as packagetype,
  cast(to_consigner_city as string) as to_consigner_city,
  cast(to_consigner_country as string) as to_consigner_country,
  cast(lane_name as string) as lane_name,
  cast(route_distance as string) as route_distance,
  cast(to_purchase_order_number as string) as to_purchase_order_number,
  cast(to_consignor_id as string) as to_consignor_id,
  cast(totalpalletsactual as string) as totalpalletsactual,
  cast(totalpalletsplaned as string) as totalpalletsplaned,
  cast(to_status as string) as to_status,
  cast(to_floor_pallets_actuals as string) as to_floor_pallets_actuals,
  cast(to_floor_pallets_planned as string) as to_floor_pallets_planned,
  cast(pickup_status as string) as pickup_status,
  cast(to_reference_number as string) as to_reference_number,
  cast(to_delivery_note_number as string) as to_delivery_note_number,
  cast(to_recipient_city as string) as to_recipient_city,
  cast(to_recipient_country as string) as to_recipient_country,
  cast(to_recipient_id as string) as to_recipient_id,
  cast(to_recipient_name as string) as to_recipient_name,
  cast(to_recipient_zipcode as string) as to_recipient_zipcode,
  cast(to_remarks as string) as to_remarks,
  cast(transport_start_date as string) as transport_start_date,
  cast(to_consigner_name as string) as to_consigner_name,
  cast(to_pallet_places as string) as to_pallet_places,
  cast(ld_transport_end_date as string) as ld_transport_end_date
from source